version: '2'
services:
  web:
    build:
      context: ./
      dockerfile: php.Dockerfile
    ports:
      - '8080:80'
      - '8443:443'
    #volumes:
      #- './src:/var/www/html'
      #- './src/composer.json:/var/www/html/composer.json'
  # postgres:
  #   build:
  #     context: _docker
  #     dockerfile: postgres.Dockerfile
  #   ports:
  #     - '9080:5432'
  #   volumes:
  #     - './_db/postgres:/docker-entrypoint-initdb.d/'
  #   environment:
  #     POSTGRES_USER: adm_ci4base
  #     POSTGRES_PASSWORD: adm_ci4base
  #     POSTGRES_DB: db_ci4base
  # adminer:
  #   image: michalhosna/adminer
  #   ports:
  #     - '6008:8080'
  #   environment:
  #     ADMINER_DRIVER: pgsql
  #     ADMINER_SERVER: postgres
  #     ADMINER_DB: db_ci4base
  #     ADMINER_PASSWORD: adm_ci4base
  #     ADMINER_USERNAME: adm_ci4base
  #     ADMINER_AUTOLOGIN: 1
  #     ADMINER_NAME: CI4-Base
